### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by rbavery** [dymaxionlabs/satproc#2]
there may be some code that can be borrowed from a very robust but unfortunately inactive project: https://github.com/CosmiQ/solaris

I assisted with turning geopandas dataframes + directories of images into COCO formatted datasets and handling issues with the overlap of label, imagery, and area mapped: https://github.com/CosmiQ/solaris/pull/316

**Comment by munshkr** [comment]
Hi @rbavery, yes, there are a lot of points in common with Solaris w.r.t goals and approach. We still have to define our development roadmap, but feel free to suggest improvements or first steps into this direction if you want to. We'd be happy to include your work here!
